In [1]:
import pandas as pd

In [7]:
x0 = 9850
digitos=4
iteracion=0
Xn=x0
Ni=10
LXn=[]
LXc=[]
Li=[]
LL=[]
LUi=[]
LRn=[]
while(iteracion<=Ni):
    Xc=int(Xn) * int(Xn)
    Xcs=str(Xc)
    while(len(Xcs) < 8):
        Xcs="0"+Xcs

    Longitud=len(Xcs)
    Ui=Xcs[int((Longitud/2)-2):int((Longitud/2)+2)]
    Nn="1"
    while(len(Nn)<(digitos+1)):
        Nn=Nn+"0"
    Rn=int(Ui)/int(Nn)    
    #print("IteraciÃ³n: ",iteracion)
    Li.append(iteracion)
    #print("Xn: ",Xn)
    LXn.append(Xn)
    #print("Xn * Xn: ",Xcs)
    LXc.append(Xcs)
    #print("Longitud: ",Longitud)
    LL.append(Longitud)
    #print("Ui: ",Ui)
    LUi.append(Ui)
    #print(Nn)
    #print("Randomico: ",Rn)
    LRn.append(Rn)
    Xn=Ui
    iteracion=iteracion+1
    
data={'Iteracion':Li,'Xn':LXn,'Xn*Xn':LXc,'Longitud':LL,'Ui':LUi,'Rn':LRn}
df=pd.DataFrame(data)
print("Semilla: ",x0)
print("Numero de Iteraciones: ",Ni)
print("Digitos: ",digitos)
df

Semilla:  9850
Numero de Iteraciones:  10
Digitos:  4

    Iteracion    Xn     Xn*Xn  Longitud    Ui      Rn
0           0  9850  97022500         8  0225  0.0225
1           1  0225  00050625         8  0506  0.0506
2           2  0506  00256036         8  2560  0.2560
3           3  2560  06553600         8  5536  0.5536
4           4  5536  30647296         8  6472  0.6472
5           5  6472  41886784         8  8867  0.8867
6           6  8867  78623689         8  6236  0.6236
7           7  6236  38887696         8  8876  0.8876
8           8  8876  78783376         8  7833  0.7833
9           9  7833  61355889         8  3558  0.3558
10         10  3558  12659364         8  6593  0.6593